### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by edouard-lopez** [ButlerLogic/action-autotag#46]
**Related:** might be related #45 

**Issue:**

```
Run butlerlogic/action-autotag@stable
  with:
    root: ./conf.d/pure.fish
    regex_pattern: pure_version\s(?<version>(\d+(\.)?){3})
    tag_prefix: v
    strategy: package
  env:
    GITHUB_TOKEN: ***
/usr/bin/docker run --name bb0998910224fb162b475f9844bfa5b68581f8_f0313a --label bb0998 --workdir /github/workspace --rm -e "GITHUB_TOKEN" -e "INPUT_ROOT" -e "INPUT_REGEX_PATTERN" -e "INPUT_TAG_PREFIX" -e "INPUT_STRATEGY" -e "INPUT_PACKAGE_ROOT" -e "INPUT_TAG_SUFFIX" -e "INPUT_TAG_MESSAGE" -e "INPUT_COMMIT_MESSAGE_TEMPLATE" -e "INPUT_VERSION" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/pure/pure":"/github/workspace" bb0998:910224fb162b475f9844bfa5b68581f8
/app/node_modules/undici/lib/handler/RetryHandler.js:29
    } = retryOptions ?? {}
                      ^

SyntaxError: Unexpected token '?'
    at Object.compileFunction (vm.js:344:18)
    at wrapSafe (internal/modules/cjs/loader.js:1048:15)
    at Module._compile (internal/modules/cjs/loader.js:1082:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/node_modules/undici/index.js:18:22)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
```

**How To Reproduce:**

See failing pipeline
https://github.com/pure-fish/pure/actions/runs/7057904486/job/19212863526

**Expected Behavior:**

See working pipeline
https://github.com/pure-fish/pure/actions/runs/6312852399

**Additional context:**

**Comment by elasticdotventures** [comment]
I stopped using stable and went to 
```
 - uses: butlerlogic/action-autotag@1.1.2
 ```
 and that seems to have fixed it
